version: "3"
services:
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    container_name: mariadb
    restart: always
    volumes:
      - mariadb_vl:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - network
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    volumes:
      - wordpress_vl:/var/www/html/
    ports:
      - "9000:9000"
    networks:
      - network
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx/
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - wordpress
    volumes:
      - wordpress_vl:/var/www/html
    ports:
      - "443:443"
    networks:
      - network
    env_file:
      - .env
  

networks:
  network:
    driver: bridge

volumes: 
  wordpress_vl:
    driver_opts:
      type: none
      o: bind
      device: /home/ojamil/data/wordpress
  mariadb_vl:
    driver_opts:
      type: none
      o: bind
      device: /home/ojamil/data/db