version: '3.3'
services:
  nginx:
    image: nginx
    container_name: ngnix
    build: ./requirements/nginx/.
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      - mariadb
    volumes:
      - wordpress-volumes:/var/www/wordpress
  mariadb:
    image: mariadb
    container_name: mariadb
    build: ./requirements/mariadb/.
    ports:
      - 3306:3306
    networks:
      - inception
  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress/.
    ports:
      - 9000:9000
    networks:
      - inception
    depends_on:
      - nginx
    volumes:
      - wordpress-volumes:/var/www/wordpress/ 

networks:
  inception:

volumes:
  wordpress-volumes:
